POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "appId": "app1",
  "deviceId": "device1",
  "locale": null,
  "username": "user2@example.com",
  "password": "example2"
}

> {%
    client.test("Login fails", function () {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}
